title: Random Thoughts of an Engineer
description: someplace to discuss stuff I like and sometimes showcase my work
show_downloads: false
google_analytics: UA-126749252-1
theme: jekyll-theme-midnight
